package com.myspace.lit;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CMRatings implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(generator = "CMRATINGS_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "CMRATINGS_ID_GENERATOR", sequenceName = "CMRATINGS_ID_SEQ")
    private java.lang.Long id;

    public CMRatings() {
    }
    
    public CMRatings(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}