package com.myspace.lit;

import com.myspace.lit.Employee;
import com.myspace.lit.Event;

rule 'New Joinee'
when
    $emp: Employee(noDaysSinceJoining == 0)
    $event: Event()
then
    modify($event) {
        setEventId(2);
        setEventDescription("Assign fresher course");
    }
end

rule '6 months refresher'
when
    $emp: Employee(noMonthsSinceJoining == 6)
    $event: Event()
then
    modify($event) {
        setEventId(3);
        setEventDescription("Assign 6 months refresher course");
    }
end
