package com.myspace.lit;

import com.myspace.lit.Employee;
import com.myspace.lit.Event;

rule 'New Joinee'
when
    $emp: Employee(noDaysSinceJoining == 0);
    $event: Event();
then
    $event.setEventId(2);
    $event.setEventDescription("Assign fresher course");
    
end

rule '6 months refresher'
when
    $emp: Employee(noMonthsSinceJoining == 6);
    $event: Event();
then
    $event.setEventId(3);
    $event.setEventDescription("Assign 6 months refresher course");
    
end
